ALTER TABLE "AbandonedCart" ALTER COLUMN "subtotal" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "AbandonedCart" ALTER COLUMN "total" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "BankAccount" ALTER COLUMN "currentBalance" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "BankStatementEntry" ALTER COLUMN "amount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "CashMovement" ALTER COLUMN "amount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "CashRegisterShift" ALTER COLUMN "openingAmount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "CashRegisterShift" ALTER COLUMN "expectedClosingAmount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "CashRegisterShift" ALTER COLUMN "actualClosingAmount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "CashRegisterShift" ALTER COLUMN "closingDifference" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Coupon" ALTER COLUMN "discountValue" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Coupon" ALTER COLUMN "minimumOrderValue" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Coupon" ALTER COLUMN "maxDiscountAmount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "CourierTrip" ALTER COLUMN "commissionAmount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "CustomerLedgerEntry" ALTER COLUMN "amount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "CustomerLedger" ALTER COLUMN "creditLimit" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "CustomerLedger" ALTER COLUMN "debtBalance" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Customer" ALTER COLUMN "avgTicket" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Customer" ALTER COLUMN "totalSpent" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "DeliveryFeeRule" ALTER COLUMN "fee" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "DeliveryFeeRule" ALTER COLUMN "minimumOrderValue" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "DeliveryFeeRule" ALTER COLUMN "freeDeliveryThreshold" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "DiningTable" ALTER COLUMN "minimumConsumption" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "FinancialClosing" ALTER COLUMN "grossRevenue" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "FinancialClosing" ALTER COLUMN "estimatedCost" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "FinancialClosing" ALTER COLUMN "estimatedProfit" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "FinancialTransaction" ALTER COLUMN "amount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "InventoryBatch" ALTER COLUMN "unitCost" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "InventoryItem" ALTER COLUMN "unitCost" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "InventoryLoss" ALTER COLUMN "financialLoss" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "LoyaltyRule" ALTER COLUMN "minOrderValue" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "MarketingSpend" ALTER COLUMN "amountSpent" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "OrderProductOption" ALTER COLUMN "priceSnapshot" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "OrderProduct" ALTER COLUMN "price" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "OrderProduct" ALTER COLUMN "unitCost" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "OrderProduct" ALTER COLUMN "lineTotal" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Order" ALTER COLUMN "subtotal" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Order" ALTER COLUMN "discountAmount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Order" ALTER COLUMN "couponDiscountAmount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Order" ALTER COLUMN "cashbackRedeemedAmount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Order" ALTER COLUMN "cashbackEarnedAmount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Order" ALTER COLUMN "deliveryFee" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Order" ALTER COLUMN "total" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Order" ALTER COLUMN "estimatedCost" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Order" ALTER COLUMN "estimatedProfit" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Order" ALTER COLUMN "changeFor" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Order" ALTER COLUMN "serviceFeeAmount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "ProductOption" ALTER COLUMN "price" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "ProductSizePrice" ALTER COLUMN "price" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Product" ALTER COLUMN "price" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Product" ALTER COLUMN "costPrice" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "PurchaseInvoice" ALTER COLUMN "totalAmount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Restaurant" ALTER COLUMN "deliveryFee" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Restaurant" ALTER COLUMN "minimumOrderValue" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Restaurant" ALTER COLUMN "freeDeliveryThreshold" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "TipClosing" ALTER COLUMN "amount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Wallet" ALTER COLUMN "balance" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Wallet" ALTER COLUMN "creditBalance" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Wallet" ALTER COLUMN "points" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Wallet" ALTER COLUMN "totalEarned" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "Wallet" ALTER COLUMN "totalRedeemed" SET DATA TYPE numeric(10, 2);